### ISSUE TITLE
Does not work with the newest version 8.2.0

### ISSUE THREAD

**Issue by JourneyOver** [PMExtra/GitCracken#1]
Error message:
```
C:\Users\JourneyOver\Desktop\Github\Main\GitCracken\GitCracken\dist\src\patcher.js:102
            throw new Error(`Can't patch ${patch.oldFileName}`);
                  ^

Error: Can't patch src/main/static/startMainProcess.js
    at Patcher.patchDirWithPatch (C:\Users\JourneyOver\Desktop\Github\Main\GitCracken\GitCracken\dist\src\patcher.js:102:19)
    at Patcher.patchDirWithFeature (C:\Users\JourneyOver\Desktop\Github\Main\GitCracken\GitCracken\dist\src\patcher.js:95:18)
    at Patcher.patchDir (C:\Users\JourneyOver\Desktop\Github\Main\GitCracken\GitCracken\dist\src\patcher.js:89:18)
    at executeActions (C:\Users\JourneyOver\Desktop\Github\Main\GitCracken\GitCracken\dist\bin\gitcracken-patcher.js:31:25)
    at Command.<anonymous> (C:\Users\JourneyOver\Desktop\Github\Main\GitCracken\GitCracken\dist\bin\gitcracken-patcher.js:87:11)
    at Command.listener (C:\Users\JourneyOver\Desktop\Github\Main\GitCracken\GitCracken\node_modules\commander\index.js:315:8)
    at Command.emit (node:events:394:28)
    at Command.parseArgs (C:\Users\JourneyOver\Desktop\Github\Main\GitCracken\GitCracken\node_modules\commander\index.js:665:12)
    at Command.parse (C:\Users\JourneyOver\Desktop\Github\Main\GitCracken\GitCracken\node_modules\commander\index.js:474:21)
    at Object.<anonymous> (C:\Users\JourneyOver\Desktop\Github\Main\GitCracken\GitCracken\dist\bin\gitcracken-patcher.js:89:6)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
    at node:internal/main/run_main_module:17:47
````

**Comment by Emily-0616** [comment]
I have the same problem

**Comment by leeyyl** [comment]
@PMExtra  The entrypoint code (src/main/static/startMainProcess.js of GitKraken source is modified.

**Comment by PMExtra** [comment]
I've noticed that. GitKraken v8.2.0 made a big refactor that caused this patch become invalid. I will research about it in this weekend, please keep v8.1.1 version for the moment.

Win : https://release.axocdn.com/win64/GitKrakenSetup-8.1.1.exe

Linux-deb : https://release.axocdn.com/linux/GitKraken-v8.1.1.deb

Linux-rpm : https://release.axocdn.com/linux/GitKraken-v8.1.1.rpm

Linux-tar.gz : https://release.axocdn.com/linux/GitKraken-v8.1.1.tar.gz

Mac : https://release.axocdn.com/darwin/GitKraken-v8.1.1.zip

**Comment by PMExtra** [comment]
@JourneyOver @Emily-0616 @leeyyl It support v8.2.0 now.  https://github.com/PMExtra/GitCracken/tree/v8.2.0

**Comment by JourneyOver** [comment]
> @JourneyOver @Emily-0616 @leeyyl It support v8.2.0 now. [`v8.2.0`](https://github.com/PMExtra/GitCracken/tree/v8.2.0?rgh-link-date=2021-12-20T13%3A59%3A37Z)

Can confirm it works as well! Thanks a bunch :D going to close this issue now.

**Comment by leeyyl** [comment]
> > @JourneyOver @Emily-0616 @leeyyl It support v8.2.0 now. [`v8.2.0`](https://github.com/PMExtra/GitCracken/tree/v8.2.0?rgh-link-date=2021-12-20T13%3A59%3A37Z)
> 
> Can confirm it works as well! Thanks a bunch :D going to close this issue now.

Good work! It works successfully.
